version: '3.3'

services:
  ghost:
    image: ghost
    restart: always
    environment:
      database__client: mysql
      database__connection__host: database
      database__connection__user: root
      database__connection__password: 98qUwlZI1OdL
      database__connection__database: ghost
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 98qUwlZI1OdL

  nginx:
    image: nginx
    restart: always
    ports:
      - 2368:2368
      - 80:80
    environment:
      - HOST_to=sv-test-host
    command: /bin/sh -c "
        touch /etc/nginx/conf.d/default.conf
        && echo 'server {' > /etc/nginx/conf.d/default.conf
        && echo 'server_name _;' >> /etc/nginx/conf.d/default.conf
        && echo 'listen 80;' >> /etc/nginx/conf.d/default.conf
        && echo 'listen 2368;' >> /etc/nginx/conf.d/default.conf
        && echo 'location / {' >> /etc/nginx/conf.d/default.conf
        && echo '    proxy_pass http://ghost:2368;' >> /etc/nginx/conf.d/default.conf
        && echo '    proxy_set_header    X-Real-IP $$remote_addr;' >> /etc/nginx/conf.d/default.conf
        && echo '    proxy_set_header    Host      $$http_host;' >> /etc/nginx/conf.d/default.conf
        && echo '    proxy_set_header    X-Forwarded-For $$proxy_add_x_forwarded_for;' >> /etc/nginx/conf.d/default.conf
        && echo '}' >> /etc/nginx/conf.d/default.conf
        && echo 'server_tokens off;' >> /etc/nginx/conf.d/default.conf
        && echo '}' >> /etc/nginx/conf.d/default.conf
        && nginx -g 'daemon off;'
      "
